### ISSUE TITLE
Windows 10 unsupported version

### ISSUE THREAD

**Issue by PiBoOTCCCP** [tinedpakgamer/mcenterdlls#3]
Hi, I got an update for my Windows. The app doesn't work and I can't roll back the update. Version 19041.1806.

**Comment by Arkham768666** [comment]
Same problem. And I started playing again today cuz I saw that the dlls were updated. Ffs.

**Comment by RicoGamingXD** [comment]
My Windows Version Incompatible 19041.1806

**Comment by Max-RM** [comment]
> Привет, я получил обновление для моей Windows. Приложение не работает, и я не могу откатить обновление. Версия 19041.1806.

Send dll to me, I will crack it using this manual https://youtu.be/oZ7IAIaj6Uc

**Comment by Max-RM** [comment]
> Hi, I got an update for my Windows. The app doesn't work and I can't roll back the update. Version 19041.1806.

Check my repo [https://github.com/Max-RM/mcenterdlls](https://github.com/Max-RM/mcenterdlls)

**Comment by PiBoOTCCCP** [comment]
> Check my repo https://github.com/Max-RM/mcenterdlls

Thank you! :)
