### ISSUE TITLE
new windows 11 version: 22621.608

### ISSUE THREAD

**Issue by uwuv3** [tinedpakgamer/mcenterdlls#5]
In System32 file: https://www.mediafire.com/file/0mntt49sewxsgoh/
In SysWOW64 file: https://www.mediafire.com/file/q37s05gdnbpipdx/

**Comment by uwuv3** [comment]
I will use the old version until the new version is installed

**Comment by uwuv3** [comment]
> 

Wait... I can't use old version?!?

**Comment by QwertyTheCoder** [comment]
@uwuv3 i will edit it

**Comment by uwuv3** [comment]
> @uwuv3 those are already modified

I don't know... I know the dll is changed every time there is an update, I threw it away from it.

**Comment by QwertyTheCoder** [comment]
> > @uwuv3 those are already modified
> 
> Sorry i messed up the dll files
> 
> I did : https://www.mediafire.com/file/x4euasbqa4oexdd/22621.608.zip/file

ummm? whats that
